import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Form from "@/components/Form";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kikisan.site</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      {/* <LandingPageTemplate /> */}
      <Form />
    </>
  );
};

export default Index;
